development:
  react_cors: true
  database:
    table: asira_borrower
    username: asirauser
    password: asirapass
    host: postgres_db
    port: "5432"
    maxlifetime: 30
    idle_conns: 10
    open_conns: 100
    sslmode: disable
    logmode: true
    timezone: Asia/Jakarta
  kafka:
    host: kafka
    port: "9092"
    user: asirauser
    pass: asirapass
    topics:
      new_loan: new_loan_request
  clients:
    admin: Z3JhZGlvczp1bHRpbXVz
    android: YW5kcm9rZXk6YW5kcm9zZWNyZXQ= # androkey:androsecret
  jwt:
    duration: 120 # in minutes
    jwt_secret: sXQ8jUMpueOvN5P3cdCR

staging:

production: