development:

staging:
  react_cors: true
  database:
    table: asira_borrower
    username: asirauser
    password: asirapass
    host: "127.0.0.1"
    port: "5432"
    maxlifetime: 30
    idle_conns: 10
    open_conns: 100
    sslmode: disable
    logmode: true
    timezone: Asia/Jakarta
  kafka:
    host: "10.148.0.3"
    port: "9092"
    user: user
    pass: oRB5KjfuHdXc
    client_id: asira
    sasl: true
    log_verbose: true
    topics:
      produces:
        for_lender: asira_borrower_to_lender_staging
      consumes:
        for_borrower: asira_lender_to_borrower_staging
  jwt:
    duration: 10080 # in minutes
    jwt_secret: sXQ8jUMpueOvN5P3cdCR
  mailer:
    host : smtp.gmail.com
    port : 587
    email : apranta123@gmail.com
    password : Animajid01
  messaging:
    key: clientkey
    secret: clientsecret
    url: http://asira.ayannah.com/api-messaging
    client_auth: /clientauth
    sms: /client/message_otp_send

production:
  react_cors: true
  database:
    table: asira_borrower
    username: asirauser
    password: asirapass
    host: "127.0.0.1"
    port: "5432"
    maxlifetime: 30
    idle_conns: 10
    open_conns: 100
    sslmode: disable
    logmode: true
    timezone: Asia/Jakarta
  kafka:
    host: "10.148.0.3"
    port: "9092"
    user: user
    pass: oRB5KjfuHdXc
    client_id: asira
    sasl: true
    log_verbose: true
    topics:
      produces:
        for_lender: asira_borrower_to_lender_staging
      consumes:
        for_borrower: asira_lender_to_borrower_staging
  jwt:
    duration: 10080 # in minutes
    jwt_secret: sXQ8jUMpueOvN5P3cdCR
  mailer:
    host : smtp.gmail.com
    port : 587
    email : apranta123@gmail.com
    password : Animajid01
  messaging:
    key: clientkey
    secret: clientsecret
    url: http://asira.ayannah.com/api-messaging
    client_auth: /clientauth
    sms: /client/message_otp_send