development:
  database:
    table: asira_db
    username: asirauser
    password: asirapass
    host: "127.0.0.1"
    port: "5432"
    maxlifetime: 30
    idle_conns: 10
    open_conns: 100
    sslmode: disable
    logmode: true
    timezone: Asia/Jakarta
  kafka:
    host: kafka-id-vm
    port: "9092"
    user: ""
    pass: ""
    log_verbose: true
    topics:
      new_loan: new_loan_request
  clients:
    admin: Z3JhZGlvczp1bHRpbXVz
    android: YW5kcm9rZXk6YW5kcm9zZWNyZXQ= # androkey:androsecret
  jwt:
    duration: 10080 # in minutes
    jwt_secret: sXQ8jUMpueOvN5P3cdCR

staging:

production: